apiVersion: v1
kind: Template
labels:
  app: ${APPLICATION_NAME}
metadata:
  name: ${APPLICATION_NAME}-pipeline-template
  annotations:
    description: A template for creating the pipeline for the ${APPLICATION_NAME} application.
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}-pipeline
  spec:
    runPolicy: SerialLatestOnly
    source:
      git:
        uri: ${SOURCE_REPO_GIT_URI}
        ref: ${SOURCE_REPO_GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: OPENSHIFT_RESOURCES_DIRECTORY
          value: cicd/resources/ocp
        - name: IMAGE_REGISTRY_NAMESPACE
          value: ${IMAGE_REGISTRY_NAMESPACE}
        - name: DEVELOPMENT_ENVIRONMENT_NAMESPACE
          value: ${DEVELOPMENT_ENVIRONMENT_NAMESPACE}
    triggers:
      - generic:
          secret: ${TRIGGER_SECRET}
        type: Generic
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name of the application (i.e. Openshift Application name).
  required: true
- name: SOURCE_REPO_GIT_URI
  displayName: URI of the source repository
  description: URI of the source repository.
  required: true
- name: SOURCE_REPO_GIT_BRANCH
  displayName: Branch of the source repository
  description: Branch of the source repository.
  required: true
- name: TRIGGER_SECRET
  displayName: The value of the secret for triggering the pipeline
  description: The value of the secret for triggering the pipeline.
  required: true
  generate: expression
  from: "trigger-secret-[a-zA-Z0-9]{12}"
- name: IMAGE_REGISTRY_NAMESPACE
  displayName: Namespace that the application image is to placed in
  description: Namespace that the application image is to placed in.
  required: true
- name: DEVELOPMENT_ENVIRONMENT_NAMESPACE
  displayName: The Namespace of the development environment
  description: The Namespace of the development environment.
  required: true
